services:
  - type: web
    name: deepface-streamlit-app
    env: python
    buildCommand: pip install uv && uv sync --frozen
    startCommand: uv run streamlit run app.py --server.port=10000 --server.address=0.0.0.0
    runtime: python
    pythonVersion: 3.10
